### ISSUE TITLE
Errors in cycle-dom rc17 when using .elements stream in isolate()

### ISSUE THREAD

**Issue by svachalek** [cyclejs/cyclejs#310]
The following program generates these errors using cycle-dom rc17. Using the stable versions built on RxJS and virtual-dom does not produce an error. Removing the call to isolate() also prevents the error.

```
index.js:6Error: Failed to execute 'querySelectorAll' on 'Element': The provided selector is empty.
    at Error (native)
    at ElementFinder.call (http://localhost:8080/main.js:3084:35)
    at http://localhost:8080/main.js:2825:114
    at composedFn (http://localhost:8080/main.js:374:20)
    at MapOperator.composedFn [as project] (http://localhost:8080/main.js:374:20)
    at MapOperator._n (http://localhost:8080/main.js:1045:31)
    at MemoryStream._add (http://localhost:8080/main.js:2005:17)
    at MapOperator._start (http://localhost:8080/main.js:1037:19)
    at Stream._add (http://localhost:8080/main.js:1320:20)
    at Stream.addListener (http://localhost:8080/main.js:1300:15)logToConsoleError @ index.js:6observer.error @ index.js:50Stream._e @ core.js:930MapOperator._n @ core.js:720MemoryStream._add @ core.js:1677MapOperator._start @ core.js:709Stream._add @ core.js:992Stream.addListener @ core.js:972XStreamAdapter.streamSubscribe @ index.js:62(anonymous function) @ index.js:37replicateMany @ index.js:36Cycle.run @ index.js:79run @ index.js:62(anonymous function) @ main.js:11__webpack_require__ @ bootstrap 5e4f5aa…:19(anonymous function) @ bootstrap 5e4f5aa…:39(anonymous function) @ bootstrap 5e4f5aa…:39
core.js:720Uncaught TypeError: Cannot read property '_e' of null
```

``` javascript
import {run} from '@cycle/xstream-run';
import {makeDOMDriver} from '@cycle/dom';
import isolate from '@cycle/isolate';
import {h} from '@cycle/dom';

function App({DOM}) {
    const e$ = DOM.select(':root').elements;
    return {DOM: e$.map(e => h('div', 'left=' + e.offsetLeft))};
}

run(isolate(App), {
    DOM: makeDOMDriver('body')
});
```

``` json
  "dependencies": {
    "@cycle/dom": "^10.0.0-rc17",
    "@cycle/isolate": "^1.2.1",
    "@cycle/xstream-run": "^1.1.0",
    "xstream": "^2.2.1"
  }
```

**Comment by staltz** [comment]
Seems like a legit bug and it's still happening with versions:
```js
"dependencies": {
  "@cycle/dom": "10.0.0-rc28",
  "@cycle/isolate": "1.3.2",
  "@cycle/xstream-run": "2.0.0",
  "xstream": "4.0.1",
}
```
Thanks for reporting

**Comment by staltz** [comment]
Fixed in the `unified` branch. Not yet released.
