### ISSUE TITLE
Exception being thrown when a driver doesn't return anything

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/cyclejs#393]
Sometimes you don't want to use a driver in a particular env. Something that worked earlier.
**Code to reproduce the issue:**
1. Create a driver `noop`
  ```js
  function noop () {}
  ```
2.  Use it in the driver, 
   ```js
   Cycle.run(Main, {AUDIO: noop})
   ```
**Expected behavior:**
Earlier it was working just fine if noop din't return anything. Right now `noop` needs to return atleast an empty object `{}`.

**Actual behavior:**
Exception is thrown

```
/Users/tushar.mathur/Documents/Projects/funag/node_modules/@cycle/base/lib/index.js:39
            sources[name_2]._isCycleSource = name_2;
                                           ^

TypeError: Cannot set property '_isCycleSource' of undefined
    at callDrivers (/Users/tushar.mathur/Documents/Projects/funag/node_modules/@cycle/base/lib/index.js:39:44)
    at Object.Cycle [as default] (/Users/tushar.mathur/Documents/Projects/funag/node_modules/@cycle/base/lib/index.js:93:19)
    at Function.run (/Users/tushar.mathur/Documents/Projects/funag/node_modules/@cycle/rx-run/lib/index.js:32:29)
    at Compiler.onEmit (AppShellPlugin.js:52:13)
    at Compiler.applyPluginsAsync (/Users/tushar.mathur/Documents/Projects/funag/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/tushar.mathur/Documents/Projects/funag/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (/Users/tushar.mathur/Documents/Projects/funag/node_modules/webpack/lib/Compiler.js:54:18)
    at /Users/tushar.mathur/Documents/Projects/funag/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/tushar.mathur/Documents/Projects/funag/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/tushar.mathur/Documents/Projects/funag/node_modules/webpack/lib/CachePlugin.js:40:4)
```

**Versions of packages used:**
@cycle/base — "version": "4.1.0"

**Comment by eshansingh** [comment]
Cannot reproduce for me on the same version. I wonder if anything else is going on?

**Comment by whitecolor** [comment]
https://github.com/cyclejs/cyclejs/blob/master/base/src/index.ts#L109
Its a bug, Andre probably forgot that driver source may bi nil

**Comment by staltz** [comment]
Yep, my silly mistake. Will fix asap.

**Comment by tusharmath** [comment]
thanks.

**Comment by tusharmath** [comment]
@staltz This hasn't been released yet?

**Comment by staltz** [comment]
Yes it has. Try using the latest versions of whatever packages you were using
