### ISSUE TITLE
Warnings from webpack: "cannot find source file" (perhaps source-map-loader)

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#577]
**Code to reproduce the issue:**

https://github.com/mightyiam/cyclejs-components/tree/65f6821c2a4a48162ded56a6568eda154fda8ce6

**Issue:**

I'm getting warnings like the following in webpack. I think it might have to do with the source-map-loader. I don't know whether [this helps](https://github.com/webpack-contrib/source-map-loader/issues/18).

They kind of make sense, because the `src` directory is not published. But I don't know how this is supposed to work, at all.

Is it a bug in this project?

```
WARNING in ./~/@cycle/history/lib/index.js                                                                                                                         
(Emitted value instead of an instance of Error) Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in '/home/shahar/src/cyclejs-comp
onents/node_modules/@cycle/history/lib'                                                                                                                            
NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in '/home/s
hahar/src/cyclejs-components/node_modules/@cycle/history/lib'                                                                                                      
    at emitWarning (/home/shahar/src/cyclejs-components/node_modules/webpack/lib/NormalModule.js:114:16)                                                           
    at /home/shahar/src/cyclejs-components/node_modules/source-map-loader/index.js:65:7                                                                            
    at onResolved (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/Resolver.js:70:11)                                                        
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)                                 
    at afterInnerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/Resolver.js:138:10)                                               
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)                                 
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/home/shahar/src/cyclejs-components/node_modules/tapable/lib/Tapable.js:181:46)                                
    at innerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/Resolver.js:125:19)                                                    
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/shahar/src/cyclejs-components/node_modules/tapable/lib/Tapable.js:283:15                          
    at /home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4                            
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/Resolver.js:138:10)                               
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/home/shahar/src/cyclejs-components/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/Resolver.js:125:19)                   
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/shahar/src/cyclejs-components/node_modules/tapable/lib/Tapable.js:283:15                                                                                  at innerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/Resolver.js:123:11)                   
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)                                     at /home/shahar/src/cyclejs-components/node_modules/tapable/lib/Tapable.js:283:15                                                              
    at resolver.doResolve.createInnerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/shahar/src/cyclejs-components/node_modules/tapable/lib/Tapable.js:188:11)                                                                       
    at innerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/Resolver.js:123:11)                   
    at loggingCallbackWrapper (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)                                 
    at /home/shahar/src/cyclejs-components/node_modules/tapable/lib/Tapable.js:283:15                          
    at resolver.doResolve.createInnerCallback (/home/shahar/src/cyclejs-components/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
 @ ./docs/index.ts 4:18-43
```

**Versions of packages used:**

@cycle/history@6.1.0

**Comment by staltz** [comment]
Hi :)
Thanks for letting us know. I took a look at your cyclejs-components project and it seems like you are using cycle/history in the correct way. I don't think there is a bug in the cycle.js package, so it's probably an issue in webpack. And I can't help you with that part unfortunately.
