### ISSUE TITLE
@cycle/run not adapting rxjs6+

### ISSUE THREAD

**Issue by jefe-spain** [cyclejs/cyclejs#832]
First of all, apologies If I am wrong or if I don't explain properly the issue. :)
Talking with @Widdershin ; seems like cycle/run not adapt properly and It returns a  `Stream` instead and instance of Observable

```
Stream {
  _prod: {},
  _ils: [],
  _stopID: {},
  _dl: {},
  _d: false,
  _target: {},
  _err: {} }

```

**Code to reproduce the issue:**

```
import { of } from 'rxjs'
import { mockTimeSource } from '@cycle/time/rxjs'
describe('Test', () => {
  it('It should emit 1', done => {
    const rxTime = mockTimeSource()
    const input$ = of(1)
    const expected$ = rxTime.diagram('(1|)')
    rxTime.assertEqual(input$, expected$)
    rxTime.run(done)
  })
})
```

**Expected behavior:**

Input stream should be equal as expected.

**Actual behavior:**

```
1) Test
       It should emit 1:
     TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
      at Object.exports.subscribeTo (node_modules/rxjs/internal/util/subscribeTo.js:42:15)
      at Object.from [as adaptStream] (node_modules/rxjs/internal/observable/from.js:18:58)
      at Object.adapt (node_modules/@cycle/run/lib/adapt.js:24:24)
      at Object.diagram (node_modules/@cycle/time/lib/cjs/src/diagram.js:50:24)
      at Context.done (main.js:8:30)
      at process.topLevelDomainCallback (domain.js:102:23)

```
**Versions of packages used:**
Tried rxjs 5.5.x and It works as expected.

  ```
  "rxjs": "^6.2.2"
    "@cycle/time": "^0.15.0"
```

**Comment by jefe-spain** [comment]
Gonna reply myself ->  Importing symbol-observable polyfill solved the issue

https://www.npmjs.com/package/symbol-observable
