### ISSUE TITLE
Cannot run dom tests 

### ISSUE THREAD

**Issue by Gastonite** [cyclejs/cyclejs#908]
Hi! Perhaps I missed something, but I can't run cycle dom tests.

It seems that pnpm doesn't install all devDependencies.

**Code to reproduce the issue:**
1. Clone the repo (92271346)
2. Execute `pnpm i && pnpm recusive i` command
3. Execute `cd dom && pnpm test`

**Expected behavior:**

tests pass

**Actual behavior:**

tests doesn't pass and i can see a strange stack trace:
```Scope: current workspace package
> @cycle/dom@22.4.0 test /lab/cyclejs/dom
> pnpm run test-node && pnpm run test-browser

Scope: current workspace package
> @cycle/dom@22.4.0 test-node /lab/cyclejs/dom
> mocha test/node/*.ts --require ts-node/register --exit

Error: Cannot find module '@cycle/rxjs-run'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/lab/cyclejs/dom/test/node/mock-dom-source.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/lab/cyclejs/node_modules/.registry.npmjs.org/ts-node/7.0.1/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/lab/cyclejs/node_modules/.registry.npmjs.org/ts-node/7.0.1/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /lab/cyclejs/node_modules/.registry.npmjs.org/mocha/6.2.0/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/lab/cyclejs/node_modules/.registry.npmjs.org/mocha/6.2.0/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/lab/cyclejs/node_modules/.registry.npmjs.org/mocha/6.2.0/node_modules/mocha/lib/mocha.js:811:10)
    at Object.exports.singleRun (/lab/cyclejs/node_modules/.registry.npmjs.org/mocha/6.2.0/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/lab/cyclejs/node_modules/.registry.npmjs.org/mocha/6.2.0/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] (/lab/cyclejs/node_modules/.registry.npmjs.org/mocha/6.2.0/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/lab/cyclejs/node_modules/.registry.npmjs.org/yargs/13.2.2/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/lab/cyclejs/node_modules/.registry.npmjs.org/yargs/13.2.2/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/lab/cyclejs/node_modules/.registry.npmjs.org/yargs/13.2.2/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/lab/cyclejs/node_modules/.registry.npmjs.org/mocha/6.2.0/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/lab/cyclejs/node_modules/.registry.npmjs.org/mocha/6.2.0/node_modules/mocha/bin/mocha:154:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Versions of packages used:**

commit 92271346
pnpm version: 3.8.1

**Comment by jvanbruegge** [comment]
Sorry that it took so long for me to answer, the solution is to run `pnpm recursive run build` before trying to test. The reason for that is that pnpm links the different cycle packages together, so without a build they will lack all the compiled files.
I created a pull request that documents this

**Comment by Gastonite** [comment]
thanks you for the explanation :)
